### PR TITLE
Document group_by and histogram feature

### PR DESCRIPTION
**Pull request by cmouse**
Ticket: DOV-3670

### CODE REVIEW

**Comment by jeffpc** [comment]
The histogram code is still in development/review, so it probably shouldn't be part of this PR.  The other stuff (group-by and cleanups) are applicable to the docs as it is now.  So, the way I see it there are two options: (1) we get histogram support done and hold off on this PR until then, or (2) split this PR into immediately applicable changes + whatever is left over for when histograms get done.

**Comment by cmouse** [comment]
This pr is part of the histogram ticket.

**Comment by jeffpc** [comment]
Ok.

**Comment by jeffpc** [comment]
Since the histogram code got a major redesign, I'm going to rewrite the documentation as well.  I'll make a new PR.

**Pull request closed without merging**
