### PR TITLE
Add/fix obox settings

### PR DESCRIPTION
**Pull request by sirainen**
DOV-3790

### CODE REVIEW

**Comment by sirainen** [comment]
I guess it's a bit bad that these pages are now being moved around, which breaks existing links to these pages. But hopefully there aren't that many such links yet? But would be nice if we did all these kind of page renames/moves rather soon..

**Comment by slusarz** [comment]
I think ease of reading the documentation is more important than maintaining links to (admittedly) deprecated pages.  Maybe on main doc.dovecot.org, we can create a 404 page that would link to base of documentation?  Or to a 404 page with a search box?

**Comment by sirainen** [comment]
I guess I'm mainly wondering about this commit: settings/dovecot_core_settings: Rename to just "core"

This isn't really changing anything except makes the URL nicer ("/settings/core/" instead of "/settings/dovecot_core_settings/"). But the setting page might have been bookmarked already by people.. The new URL makes more sense though :)

**Comment by slusarz** [comment]
"But the setting page might have been bookmarked already by people.. The new URL makes more sense though :)"
And that's why the 404 page solution can handle these (isolated) cases.  A broken bookmark is fairly painless if the user has an easy way to redirect themselves to the expected content.

**Comment by thuovila** [comment]
In case we want to preserve, or not break, some specific old page names, we could look into using https://github.com/sphinx-contrib/redirects

**Pull request merged**
