### PR TITLE
settings: imap_urlauth_host is required for URLAUTH to be active

### PR DESCRIPTION
**Pull request by slusarz**
DOP-1709

### CODE REVIEW

**Comment by sirainen** [comment]
Should we also warn that URLAUTH is more or less broken now?

**Comment by slusarz** [comment]
> Should we also warn that URLAUTH is more or less broken now?

Done.

**Comment by sirainen** [comment]
nits commit should be squashed with something..

**Comment by cmouse** [comment]
Please update commit messages to conform normal commit style.

**Review by sirainen — APPROVED** [review]

**Pull request merged**
