### PR TITLE
Fixing mind-slip titles to match both intent and filename

### PR DESCRIPTION
**Pull request by grinapo**
Someone clearly in love with Postfix ;-)

### CODE REVIEW

**Comment by cmouse** [comment]
Can you please squash your commits, as they clearly are about one and same thing?

**Comment by grinapo** [comment]
> Can you please squash your commits, as they clearly are about one and same thing?

I do not use git so I don't _know_ how (this was created by github) but I'll look around in git manpages. I remember it being a dreadful experience but maybe I need a step out of my comfort zone.

**Comment by grinapo** [comment]
I am not sure this is what you meant, but looks like  commit 856eb53 is merged. 
Is that what you desired or shall I recreate this two lines?

**Review by sirainen — APPROVED** [review]

**Comment by sirainen** [comment]
Looks like that worked nicely, except I typoed howto :(

**Pull request merged**
