### PR TITLE
Move mail_crypt_curve to the correct section

### PR DESCRIPTION
**Pull request by jonmoesli**

### CODE REVIEW

**Comment by cmouse** [comment]
Can you please update commit message(s) to reflect on what the change(s) are, e.g.

`mail_crypt_plugin: Move documentation to correct place`

**Comment by jonmoesli** [comment]
I use the github interface, I don't know how do it :-(

**Comment by cmouse** [comment]
I can rewrite your commits and push them.

**Comment by jonmoesli** [comment]
Ok, thank you :-)

**Comment by cmouse** [comment]
Replaced with #174

**Pull request closed without merging**
