### PR TITLE
configuration_manual/quick_configuration: Add passdb and userdb name

### PR DESCRIPTION
**Pull request by vmo69**

### CODE REVIEW

**Review by cmouse — APPROVED** [review]

**Review by cmouse — CHANGES_REQUESTED** [review]
could remove the driver from the example maybe and add comment that driver is implied from name, but can be different and driver needs to be specified.

**Comment by vmo69** [comment]
> could remove the driver from the example maybe and add comment that driver is implied from name, but can be different and driver needs to be specified.

But that is only in config-rewrite not yet in main right? I can add that fix to config-rewrite branch. So when that is merged it is like that?

**Comment by vmo69** [comment]
> > could remove the driver from the example maybe and add comment that driver is implied from name, but can be different and driver needs to be specified.
> 
> But that is only in config-rewrite not yet in main right? I can add that fix to config-rewrite branch. So when that is merged it is like that?

In config rewrite this already looks like this:
```
 # if you want to use system users
  passdb pam {
  }

  userdb passwd {
    use_worker = no
    fields {
      uid = vmail
      gid = vmail
    }
  }
  ```

**Comment by cmouse** [comment]
oh right it's going to main...

**Review by cmouse — APPROVED** [review]

**Pull request merged**
