### PR TITLE
settings/core: small ungrammaticality/typo

### PR DESCRIPTION
**Pull request by AvdN**

### CODE REVIEW

**Review by sirainen — CHANGES_REQUESTED** [review]
Could you add `settings/core: ` prefix to the commit message? Makes reading the git log a bit easier.

**Comment by cmouse** [comment]
ping @avdn

**Comment by AvdN** [comment]
> ping @AvdN

As you can see I edited the pull request title some time ago but you seem to want the commit message. So I assumed the ping was to remind me that the commit message was not updated. 
According to https://stackoverflow.com/questions/10728420/editing-the-git-commit-message-in-github I needed to amend the message so:
- I installed ``git``
- pulled the repository from my account on github
- checked out origin/patch-1
- could finally see the commit in the log
- ran git config to set me name and my email address
- finally could run `git --amend`
- forced a push back to github
- checked changes arrived

The commit message is now updated https://github.com/dovecot/documentation/compare/main...AvdN:patch-1

**Comment by cmouse** [comment]
it's still missing the `settings/core: ` prefix, though.

**Comment by cmouse** [comment]
hm. I can see it in your repo, but not on this pull request.

**Comment by cmouse** [comment]
> hm. I can see it in your repo, but not on this pull request.

becasuse the commit is still missing it

**Comment by AvdN** [comment]
> > hm. I can see it in your repo, but not on this pull request.
> 
> becasuse the commit is still missing it

Maybe it is easier to just make the change in a new commit + PR?

**Pull request closed without merging**
