### PR TITLE
admin_manual/event_design: Fix category name syntax and small formatt…

### PR DESCRIPTION
**Pull request by sirainen**
…ing fixes.

### CODE REVIEW

**Comment by jeffpc** [comment]
Why are categories supposed to use - and fields and names _?

**Comment by sirainen** [comment]
* Because that's how they were already done, so can't change them anymore.
 * Binary/process names use '-' and they're part of category names often. So for example "imap-urlauth" service is for "imap-urlauth" process.
 * Also service names use '-' like "dict-async" which is visible as "service:dict-async" category. (I was wondering whether to mention this ':' in category names or not in this documentation .. but it's added internally, and shouldn't be added by anyone adding new categories.)

**Comment by jeffpc** [comment]
Sort of sucks that we have this inconsistency.  Oh well.

We should document that : can appear but cannot be used - in case someone tries to make a parser/validator.

**Comment by sirainen** [comment]
Added a note about ':' being used.

**Pull request merged**
